name: build-and-push
author: jhony
description: build and push to latest docker image
runs:
  using: 'composite'
  inputs:
    dockerhub_username:
      description: 'Docker Hub username'
      required: true

    dockerhub_token:
      description: 'Docker Hub login token'
      required: true

    dockerhub_repo:
      description: 'Docker Hub repository name'
      required: true
  steps:
    - uses: actions/checkout@v5

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_token }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ inputs.dockerhub_repo }}:latest